/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PunishmentRouteImport } from './routes/punishment'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SkinchangerRouteImport } from './routes/skinchanger'
import { Route as SteamfinderRouteImport } from './routes/steamfinder'
import { Route as StoreRouteImport } from './routes/store'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthSteamRouteImport } from './routes/auth.steam'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PunishmentRoute = PunishmentRouteImport.update({
  id: '/punishment',
  path: '/punishment',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinchangerRoute = SkinchangerRouteImport.update({
  id: '/skinchanger',
  path: '/skinchanger',
  getParentRoute: () => rootRouteImport,
} as any)
const SteamfinderRoute = SteamfinderRouteImport.update({
  id: '/steamfinder',
  path: '/steamfinder',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSteamRoute = AuthSteamRouteImport.update({
  id: '/auth/steam',
  path: '/auth/steam',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/punishment': typeof PunishmentRoute
  '/rules': typeof RulesRoute
  '/skinchanger': typeof SkinchangerRoute
  '/steamfinder': typeof SteamfinderRoute
  '/store': typeof StoreRoute
  '/tickets': typeof TicketsRoute
  '/verify': typeof VerifyRoute
  '/auth/steam': typeof AuthSteamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/punishment': typeof PunishmentRoute
  '/rules': typeof RulesRoute
  '/skinchanger': typeof SkinchangerRoute
  '/steamfinder': typeof SteamfinderRoute
  '/store': typeof StoreRoute
  '/tickets': typeof TicketsRoute
  '/verify': typeof VerifyRoute
  '/auth/steam': typeof AuthSteamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/punishment': typeof PunishmentRoute
  '/rules': typeof RulesRoute
  '/skinchanger': typeof SkinchangerRoute
  '/steamfinder': typeof SteamfinderRoute
  '/store': typeof StoreRoute
  '/tickets': typeof TicketsRoute
  '/verify': typeof VerifyRoute
  '/auth/steam': typeof AuthSteamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/leaderboard'
    | '/profile'
    | '/punishment'
    | '/rules'
    | '/skinchanger'
    | '/steamfinder'
    | '/store'
    | '/tickets'
    | '/verify'
    | '/auth/steam'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/leaderboard'
    | '/profile'
    | '/punishment'
    | '/rules'
    | '/skinchanger'
    | '/steamfinder'
    | '/store'
    | '/tickets'
    | '/verify'
    | '/auth/steam'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/leaderboard'
    | '/profile'
    | '/punishment'
    | '/rules'
    | '/skinchanger'
    | '/steamfinder'
    | '/store'
    | '/tickets'
    | '/verify'
    | '/auth/steam'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProfileRoute: typeof ProfileRoute
  PunishmentRoute: typeof PunishmentRoute
  RulesRoute: typeof RulesRoute
  SkinchangerRoute: typeof SkinchangerRoute
  SteamfinderRoute: typeof SteamfinderRoute
  StoreRoute: typeof StoreRoute
  TicketsRoute: typeof TicketsRoute
  VerifyRoute: typeof VerifyRoute
  AuthSteamRoute: typeof AuthSteamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/punishment': {
      id: '/punishment'
      path: '/punishment'
      fullPath: '/punishment'
      preLoaderRoute: typeof PunishmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skinchanger': {
      id: '/skinchanger'
      path: '/skinchanger'
      fullPath: '/skinchanger'
      preLoaderRoute: typeof SkinchangerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steamfinder': {
      id: '/steamfinder'
      path: '/steamfinder'
      fullPath: '/steamfinder'
      preLoaderRoute: typeof SteamfinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/steam': {
      id: '/auth/steam'
      path: '/auth/steam'
      fullPath: '/auth/steam'
      preLoaderRoute: typeof AuthSteamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfileRoute: ProfileRoute,
  PunishmentRoute: PunishmentRoute,
  RulesRoute: RulesRoute,
  SkinchangerRoute: SkinchangerRoute,
  SteamfinderRoute: SteamfinderRoute,
  StoreRoute: StoreRoute,
  TicketsRoute: TicketsRoute,
  VerifyRoute: VerifyRoute,
  AuthSteamRoute: AuthSteamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
